name: setup-ruby-test

on:
  workflow_dispatch:
  push:

jobs:
  ruby-action-test:
    runs-on: ubuntu-latest-ppc64le
    strategy:
      matrix:
        ruby: ['3.1.4', '3.3.0']
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: |
        bundle exec rake
        ruby -v
