name: setup-ruby-test

on:
  workflow_dispatch:
  push:

jobs:
  ruby-action-test:
    runs-on: ubuntu-22-ppc64le
    strategy:
      matrix:
        ruby: ['3.3.0']
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        self-hosted: true
    - run: |
        ruby -v
        bundle install
        bundle exec ruby hello.rb
