name: setup-ruby-test

on:
  workflow_dispatch:
  push:

jobs:
  ruby-action-test:
    runs-on: ubuntu-22-ppc64le
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu22
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        self-hosted: true
    - run: |
        bundle exec rake
        ruby -v
